### ISSUE TITLE
EZLib won't create new program.

### ISSUE THREAD

**Issue by Rokishon** [developer-variety/EZLib-Issues#11]
Title says it all, tried making new program, when I hit create it just brings me back to the programs page while not creating the program, I made sure to put 1.0.0 so idk...

**Comment by developer-variety** [comment]
This bug is like a plaque. It keeps coming back. Looking into it.

**Comment by developer-variety** [comment]
This issue has been resolved.

I'll be closing this issue, if you have anymore concerns about this you can send me an email at developer.variety@gmail.com

Sincerely, Justin.
