### ISSUE TITLE
Serial Registration

### ISSUE THREAD

**Issue by ghost** [developer-variety/EZLib-Issues#12]
I am adding an extra step to serial registration. In order for the Developer to see someone's information or anything like that the user first has to register their serial. This is kind of security issue and also a good enhancement to the system.

TODO:
- [x] Add registered to database table
- [x] Check if serial is registered on API

**Comment by developer-variety** [comment]
Completed `Add registered to database table`.

**Comment by developer-variety** [comment]
This is solved.
