### ISSUE TITLE
Exception thrown after 3 minutes

### ISSUE THREAD

**Issue by CyberAFG** [developer-variety/EZLib-Issues#14]
Exception thrown after 3 mins of nothing.
>Logged In>3 Mins>Exception
System.Exception: 'An unknown error occurred. This application must terminate.'
Source Not Available
Source information is missing from the debug information for this module.
"You can view disassembly in the Disassembly window.

**Comment by developer-variety** [comment]
I believe this is a bug in getting real-time data. I'll be looking into it, thanks for reporting it.

**Comment by developer-variety** [comment]
I am still looking into this bug. I've identified it, and looking into other methods to get real-time data.

**Comment by developer-variety** [comment]
This issue has been fixed.

It will be released in the upcoming update 1.0.1
