### ISSUE TITLE
Panel: Cant Download Examaple

### ISSUE THREAD

**Issue by GodSpeed2323** [developer-variety/EZLib-Issues#2]
Hey so I pressed the download button for example and there is no download

https://www.ezlib.rocks/download?example=true

that is the url thanks!

**Comment by developer-variety** [comment]
I'll be adding it shortly! Its Christmas Eve where I live so family is here.

**Comment by GodSpeed2323** [comment]
ah same here but no worries, should add the code needed for the Dll in Downloads
incase of bugs!

**Comment by developer-variety** [comment]
What's wrong with dll download?

**Comment by GodSpeed2323** [comment]
not dll but say https://www.ezlib.rocks/download?example=true does not work
instead of using the code in the example the code can just be on the php page for easier access

**Comment by developer-variety** [comment]
Oh so pretty much like documentation?

**Comment by GodSpeed2323** [comment]
yes

**Comment by developer-variety** [comment]
Ah yes, it's on the to-do list of mine.

**Comment by GodSpeed2323** [comment]
awesome 👍

**Comment by developer-variety** [comment]
Make sure to use the EZLib Discord bot if you have Discord! Makes life much easier.

**Comment by GodSpeed2323** [comment]
yep already have it just waiting for code :)

**Comment by developer-variety** [comment]
I'll be closing this issue, if you have anymore concerns about this you can send me an email at `developer.variety@gmail.com`.

This issues has been resolved.

Sincerely, Justin.
