### ISSUE TITLE
EZLib Obfuse

### ISSUE THREAD

**Issue by ghost** [developer-variety/EZLib-Issues#5]
I have to get the systems for this up and running quickly. After all of these are done EZLib Obfuse will be public.

TODO:
- [x] Points system
- [x] Redeem codes
- [x] Buy codes
- [x] Transfer unobfuscated file to obfuse server
- [x] Obfuse file
- [x] Transfer obfuscated file back to main server

**Comment by developer-variety** [comment]
Completed `Redeem code system`.

**Comment by developer-variety** [comment]
Completed `Transfer unobfuscated files to obfuse server`.

**Comment by developer-variety** [comment]
Completed `Transfer obfuscated file back to main server`.

**Comment by developer-variety** [comment]
Completed `Buy codes`.

**Comment by kekguy** [comment]
Ezlib i down

**Comment by developer-variety** [comment]
Completed `Obfuse file`.

This feature has been completed. Within release date of EZLib 1.0.0 there will be a client for all developers to download to use EZLib Obfuse.
