### ISSUE TITLE
Improve EZLib Bot

### ISSUE THREAD

**Issue by ghost** [developer-variety/EZLib-Issues#7]
I would like to improve the EZLib Discord bot to be more efficient and more noob-friendly. Recode the entire bot with Discord JS.

TODO:
- [ ] Ask for parameters one by one

Cleanup commands:
- [ ] About
- [ ] Link
- [ ] Generate
- [ ] Ban
- [ ] Unban
- [ ] Info

**Comment by developer-variety** [comment]
Cleaned up `About` and `Link` commands.

**Comment by developer-variety** [comment]
This is delayed.
